-- Add idCiclo column to CONCEPTO_PAGO table
ALTER TABLE "CONCEPTO_PAGO" ADD COLUMN "idCiclo" INTEGER NOT NULL DEFAULT 1;

-- Add foreign key constraint
ALTER TABLE "CONCEPTO_PAGO" ADD CONSTRAINT "CONCEPTO_PAGO_idCiclo_fkey" FOREIGN KEY ("idCiclo") REFERENCES "CICLO_LECTIVO"("idCiclo") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Add unique constraint on (idCiclo, nombre)
ALTER TABLE "CONCEPTO_PAGO" DROP CONSTRAINT IF EXISTS "CONCEPTO_PAGO_nombre_key";
ALTER TABLE "CONCEPTO_PAGO" ADD CONSTRAINT "CONCEPTO_PAGO_idCiclo_nombre_key" UNIQUE("idCiclo", "nombre");
