-- CreateTable
CREATE TABLE "PERSONA" (
    "idPersona" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nombre" TEXT NOT NULL,
    "apellido" TEXT NOT NULL,
    "dni" TEXT NOT NULL,
    "telefono" TEXT,
    "direccion" TEXT,
    "email" TEXT
);

-- CreateTable
CREATE TABLE "USUARIO" (
    "idUsuario" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "idPersona" INTEGER NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "estado" BOOLEAN NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "USUARIO_idPersona_fkey" FOREIGN KEY ("idPersona") REFERENCES "PERSONA" ("idPersona") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "ROL" (
    "idRol" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nombre" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "USUARIO_ROL" (
    "idUsuario" INTEGER NOT NULL,
    "idRol" INTEGER NOT NULL,

    PRIMARY KEY ("idUsuario", "idRol"),
    CONSTRAINT "USUARIO_ROL_idUsuario_fkey" FOREIGN KEY ("idUsuario") REFERENCES "USUARIO" ("idUsuario") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "USUARIO_ROL_idRol_fkey" FOREIGN KEY ("idRol") REFERENCES "ROL" ("idRol") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "ALUMNO" (
    "idAlumno" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "idPersona" INTEGER NOT NULL,
    "fechaNacimiento" DATETIME NOT NULL,
    "legajo" TEXT NOT NULL,
    CONSTRAINT "ALUMNO_idPersona_fkey" FOREIGN KEY ("idPersona") REFERENCES "PERSONA" ("idPersona") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PROFESOR" (
    "idProfesor" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "idPersona" INTEGER NOT NULL,
    "fechaIngreso" DATETIME NOT NULL,
    CONSTRAINT "PROFESOR_idPersona_fkey" FOREIGN KEY ("idPersona") REFERENCES "PERSONA" ("idPersona") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PADRE" (
    "idPadre" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "idPersona" INTEGER NOT NULL,
    CONSTRAINT "PADRE_idPersona_fkey" FOREIGN KEY ("idPersona") REFERENCES "PERSONA" ("idPersona") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "ALUMNO_PADRE" (
    "idAlumno" INTEGER NOT NULL,
    "idPadre" INTEGER NOT NULL,
    "relacion" TEXT NOT NULL,

    PRIMARY KEY ("idAlumno", "idPadre"),
    CONSTRAINT "ALUMNO_PADRE_idAlumno_fkey" FOREIGN KEY ("idAlumno") REFERENCES "ALUMNO" ("idAlumno") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "ALUMNO_PADRE_idPadre_fkey" FOREIGN KEY ("idPadre") REFERENCES "PADRE" ("idPadre") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "CICLO_LECTIVO" (
    "idCiclo" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "anio" INTEGER NOT NULL,
    "estado" BOOLEAN NOT NULL
);

-- CreateTable
CREATE TABLE "PERIODO_ACADEMICO" (
    "idPeriodo" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "idCiclo" INTEGER NOT NULL,
    "nombre" TEXT NOT NULL,
    "fechaInicio" DATETIME NOT NULL,
    "fechaFin" DATETIME NOT NULL,
    CONSTRAINT "PERIODO_ACADEMICO_idCiclo_fkey" FOREIGN KEY ("idCiclo") REFERENCES "CICLO_LECTIVO" ("idCiclo") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "CURSO" (
    "idCurso" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "grado" TEXT NOT NULL,
    "seccion" TEXT NOT NULL,
    "nivel" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "MATERIA" (
    "idMateria" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nombre" TEXT NOT NULL,
    "descripcion" TEXT
);

-- CreateTable
CREATE TABLE "ASIGNACION_ACADEMICA" (
    "idAsignacion" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "idProfesor" INTEGER NOT NULL,
    "idMateria" INTEGER NOT NULL,
    "idCurso" INTEGER NOT NULL,
    "idCiclo" INTEGER NOT NULL,
    "cargaHoraria" INTEGER NOT NULL,
    CONSTRAINT "ASIGNACION_ACADEMICA_idProfesor_fkey" FOREIGN KEY ("idProfesor") REFERENCES "PROFESOR" ("idProfesor") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "ASIGNACION_ACADEMICA_idMateria_fkey" FOREIGN KEY ("idMateria") REFERENCES "MATERIA" ("idMateria") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "ASIGNACION_ACADEMICA_idCurso_fkey" FOREIGN KEY ("idCurso") REFERENCES "CURSO" ("idCurso") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "ASIGNACION_ACADEMICA_idCiclo_fkey" FOREIGN KEY ("idCiclo") REFERENCES "CICLO_LECTIVO" ("idCiclo") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "HORARIO" (
    "idHorario" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "idAsignacion" INTEGER NOT NULL,
    "diaSemana" TEXT NOT NULL,
    "horaInicio" DATETIME NOT NULL,
    "horaFin" DATETIME NOT NULL,
    "turno" TEXT NOT NULL,
    "aula" TEXT,
    CONSTRAINT "HORARIO_idAsignacion_fkey" FOREIGN KEY ("idAsignacion") REFERENCES "ASIGNACION_ACADEMICA" ("idAsignacion") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "MATRICULA" (
    "idMatricula" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "idAlumno" INTEGER NOT NULL,
    "idCurso" INTEGER NOT NULL,
    "idCiclo" INTEGER NOT NULL,
    "fechaInscripcion" DATETIME NOT NULL,
    "estadoAcademico" TEXT NOT NULL,
    "promedioFinal" REAL,
    CONSTRAINT "MATRICULA_idAlumno_fkey" FOREIGN KEY ("idAlumno") REFERENCES "ALUMNO" ("idAlumno") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "MATRICULA_idCurso_fkey" FOREIGN KEY ("idCurso") REFERENCES "CURSO" ("idCurso") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "MATRICULA_idCiclo_fkey" FOREIGN KEY ("idCiclo") REFERENCES "CICLO_LECTIVO" ("idCiclo") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "NOTA" (
    "idNota" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "idMatricula" INTEGER NOT NULL,
    "idAsignacion" INTEGER NOT NULL,
    "idPeriodo" INTEGER NOT NULL,
    "tipo" TEXT NOT NULL,
    "nota" REAL NOT NULL,
    "observacion" TEXT,
    "fechaRegistro" DATETIME NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "NOTA_idMatricula_fkey" FOREIGN KEY ("idMatricula") REFERENCES "MATRICULA" ("idMatricula") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "NOTA_idAsignacion_fkey" FOREIGN KEY ("idAsignacion") REFERENCES "ASIGNACION_ACADEMICA" ("idAsignacion") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "NOTA_idPeriodo_fkey" FOREIGN KEY ("idPeriodo") REFERENCES "PERIODO_ACADEMICO" ("idPeriodo") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "ASISTENCIA" (
    "idAsistencia" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "idMatricula" INTEGER NOT NULL,
    "idHorario" INTEGER NOT NULL,
    "fecha" DATETIME NOT NULL,
    "estado" TEXT NOT NULL,
    "idUsuario" INTEGER NOT NULL,
    "fechaRegistro" DATETIME NOT NULL,
    CONSTRAINT "ASISTENCIA_idMatricula_fkey" FOREIGN KEY ("idMatricula") REFERENCES "MATRICULA" ("idMatricula") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "ASISTENCIA_idHorario_fkey" FOREIGN KEY ("idHorario") REFERENCES "HORARIO" ("idHorario") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "ASISTENCIA_idUsuario_fkey" FOREIGN KEY ("idUsuario") REFERENCES "USUARIO" ("idUsuario") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "CUOTA" (
    "idCuota" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "idMatricula" INTEGER NOT NULL,
    "mes" INTEGER NOT NULL,
    "montoOriginal" REAL NOT NULL,
    "saldo" REAL NOT NULL,
    "fechaVencimiento" DATETIME NOT NULL,
    "estado" TEXT NOT NULL,
    CONSTRAINT "CUOTA_idMatricula_fkey" FOREIGN KEY ("idMatricula") REFERENCES "MATRICULA" ("idMatricula") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PAGO" (
    "idPago" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "idCuota" INTEGER NOT NULL,
    "fechaPago" DATETIME NOT NULL,
    "monto" REAL NOT NULL,
    "medioPago" TEXT NOT NULL,
    "comprobante" TEXT,
    "idUsuario" INTEGER NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PAGO_idCuota_fkey" FOREIGN KEY ("idCuota") REFERENCES "CUOTA" ("idCuota") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "PAGO_idUsuario_fkey" FOREIGN KEY ("idUsuario") REFERENCES "USUARIO" ("idUsuario") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "COMUNICADO" (
    "idComunicado" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "titulo" TEXT NOT NULL,
    "contenido" TEXT NOT NULL,
    "fecha" DATETIME NOT NULL,
    "idUsuario" INTEGER NOT NULL,
    CONSTRAINT "COMUNICADO_idUsuario_fkey" FOREIGN KEY ("idUsuario") REFERENCES "USUARIO" ("idUsuario") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "INVENTARIO" (
    "idInsumo" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nombre" TEXT NOT NULL,
    "stockActual" INTEGER NOT NULL,
    "stockMinimo" INTEGER NOT NULL,
    "unidadMedida" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "MOVIMIENTO_STOCK" (
    "idMovimiento" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "idInsumo" INTEGER NOT NULL,
    "idUsuario" INTEGER NOT NULL,
    "tipo" TEXT NOT NULL,
    "cantidad" INTEGER NOT NULL,
    "fecha" DATETIME NOT NULL,
    CONSTRAINT "MOVIMIENTO_STOCK_idInsumo_fkey" FOREIGN KEY ("idInsumo") REFERENCES "INVENTARIO" ("idInsumo") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "MOVIMIENTO_STOCK_idUsuario_fkey" FOREIGN KEY ("idUsuario") REFERENCES "USUARIO" ("idUsuario") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "GASTO_INSTITUCIONAL" (
    "idGasto" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "idUsuario" INTEGER NOT NULL,
    "monto" REAL NOT NULL,
    "fecha" DATETIME NOT NULL,
    "concepto" TEXT NOT NULL,
    "categoria" TEXT NOT NULL,
    "idMovimiento" INTEGER,
    CONSTRAINT "GASTO_INSTITUCIONAL_idUsuario_fkey" FOREIGN KEY ("idUsuario") REFERENCES "USUARIO" ("idUsuario") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "GASTO_INSTITUCIONAL_idMovimiento_fkey" FOREIGN KEY ("idMovimiento") REFERENCES "MOVIMIENTO_STOCK" ("idMovimiento") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "PERSONA_dni_key" ON "PERSONA"("dni");

-- CreateIndex
CREATE UNIQUE INDEX "USUARIO_idPersona_key" ON "USUARIO"("idPersona");

-- CreateIndex
CREATE UNIQUE INDEX "ALUMNO_idPersona_key" ON "ALUMNO"("idPersona");

-- CreateIndex
CREATE UNIQUE INDEX "ALUMNO_legajo_key" ON "ALUMNO"("legajo");

-- CreateIndex
CREATE UNIQUE INDEX "PROFESOR_idPersona_key" ON "PROFESOR"("idPersona");

-- CreateIndex
CREATE UNIQUE INDEX "PADRE_idPersona_key" ON "PADRE"("idPersona");

-- CreateIndex
CREATE UNIQUE INDEX "CICLO_LECTIVO_anio_key" ON "CICLO_LECTIVO"("anio");

-- CreateIndex
CREATE UNIQUE INDEX "PERIODO_ACADEMICO_idCiclo_nombre_key" ON "PERIODO_ACADEMICO"("idCiclo", "nombre");

-- CreateIndex
CREATE UNIQUE INDEX "ASIGNACION_ACADEMICA_idMateria_idCurso_idCiclo_key" ON "ASIGNACION_ACADEMICA"("idMateria", "idCurso", "idCiclo");

-- CreateIndex
CREATE UNIQUE INDEX "MATRICULA_idAlumno_idCiclo_key" ON "MATRICULA"("idAlumno", "idCiclo");

-- CreateIndex
CREATE UNIQUE INDEX "CUOTA_idMatricula_mes_key" ON "CUOTA"("idMatricula", "mes");
